### ISSUE TITLE
Known issue: station details outdated

### ISSUE THREAD

**Issue by vingerha** [Aohzan/hass-prixcarburant#1]
The details of the stations are derived from a file, see link below
This file is not maintained and has not been updated since years, as a result your stations may show an old name or no name at all.
dd. 30/6/2022 there seems to be no other centralized solution providing the same data in manageable format.
This remains open issue until such a solution is provided by the French government or if someone (else) takes provides a workaround.

Suggestions are welcome

https://static.data.gouv.fr/resources/prix-des-carburants-en-france/20181117-111538/active-stations.csv

**Comment by Zehir** [comment]
Could you display the station address instead of his ID when the name is unavaliable ?
And about the entity ID, maybe keep the station ID in case the name change at some point ?

**Comment by Zehir** [comment]
You can also fetch data like them and store them in this repo;
https://github.com/floman321/prixcarburants/tree/master/data/listestations

**Comment by vingerha** [comment]
@Zehir 
1. showing the address: the address is part of the sensor so displaying that is a matter of configuring the output. This is imo not something that this integration should provide on top.
2. On the link, I verified the API that @roumano sent on a station close to me. The API does not show the station name, just address and services. The github link is showing more and FINALLY the name of my station. However, I am worried about the validity of this data, i.e. is this complete and will it be maintained? My questions towards extending the API provider run dead as they usually do with gouv stuff...but it should actually be the single source of truth, not something that depends on the work of a single person like floman321

**Comment by Zehir** [comment]
Floman just scrape the stations names, the related code is provided. I think it's better than a file from 2016

**Comment by vingerha** [comment]
Anything is better than that file but this is what the original implementation was based on. 
If you would ask me how to progress, I would say that this fork needs to incorporate the scrape results, to not depend on someone else...but it is quite a bit of work I guess, so tbd by Matthieu / @Aohzan

**Comment by Aohzan** [comment]
If I understand, we should migrate to [this API](https://data.economie.gouv.fr/explore/dataset/prix-carburants-fichier-instantane-test-ods-copie/api/). :+1: 
But to get the station name, we have to use something like [this](https://github.com/DuchkPy/fr.prix-carburants/blob/master/stations.py), which is webscraping :nauseated_face:

**Comment by vingerha** [comment]
So, from what I know and have read above only (!) the webscraping provides the station name, currently downloaded in floman321 github. The api does not bring any additional important (!) info ... for as far as I can see
I also donot know why that site's data is not available as api but I could not find it and neither can others, leading to the webscrape.

**Comment by Zehir** [comment]
And what about using an other api like this ? https://api.zagaz.com/

**Comment by Aohzan** [comment]
As it's a different data source, which need a api key from the users, I think it has to be a new separate integration

**Comment by Aohzan** [comment]
Otherwise we put the address in the station name and we let the user renames them ?

**Comment by vingerha** [comment]
Why would this be needed, the user can select its choice from the attributes? I see that you might liek this but I am not sure if this serves all others. The examples of the tables I added also show the address... donot see the added value

**Comment by Aohzan** [comment]
version 3.0.0 fix this
