### ISSUE TITLE
Add service to get nearest stations prices from mobile/device_tracker location

### ISSUE THREAD

**Issue by titof2375** [Aohzan/hass-prixcarburant#10]
hello can you hope that your integration can take the coordinates of a mobile phone to make a data the cheapest gas station?

**Comment by Aohzan** [comment]
maybe it's possible, I will check that

**Comment by Aohzan** [comment]
in next beta
![image](https://github.com/Aohzan/hass-prixcarburant/assets/2736322/8918c972-a43b-478f-a99d-38061348958a)

**Comment by pbranly** [comment]
Hi
Cela ne fonctionne plus 
J'ai cette erreur:
![image](https://github.com/Aohzan/hass-prixcarburant/assets/22018509/0437ffec-a61b-4a03-91aa-8b62f840cc7b)

**Comment by Aohzan** [comment]
toujours mettre les logs d'erreur svp
je viens de push une b4

**Comment by pbranly** [comment]
Ça re fonctionne en b4 merci 
Reste à retrouver les distances sur ma carte 
![image](https://github.com/Aohzan/hass-prixcarburant/assets/22018509/d127a5ea-1040-419e-aaa6-a5ca4c6a9a0a)

**Comment by Aohzan** [comment]
distance remise
