### ISSUE TITLE
Passage au flux instantané v2

### ISSUE THREAD

**Issue by Emeraude998** [Aohzan/hass-prixcarburant#11]
J'utilise l'intégration Prix Carburant depuis maintenant plus de 4 mois et n'ai pas eu de souci d'ici à cette semaine.
Toutes les entités qui avaient été trouvées (56 stations et plus d'une centaine d'entités) sont devenues **Unavailable**. 
Recharger l'intégration n'aide pas et redemarrer mon instance de Home Assistant ne fait rien non plus.

Dans les logs, je trouve les erreurs suivantes :
```
2023-10-01 05:00:00.112 ERROR (MainThread) [custom_components.prix_carburant.sensor] Error requesting prix_carburant data: HTTP Error 502: Bad Gateway
2023-10-01 05:00:00.113 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up prix_carburant platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/prix_carburant/sensor.py", line 103, in async_setup_entry
raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None
```

Pourrais-tu m'aider à résoudre ce problème ?

**Comment by pbranly** [comment]
Même soucis de mon côté . Ça marchait jusqu'à hier

**Comment by Emeraude998** [comment]
Après de plus amples recherches, il semblerait que le problème vienne du site web https://donnees.roulez-eco.fr/opendata/instantane qui n'est plus maintenu.
Il renvoie maintenant une erreur `502 Bad Gateway` ou `504 Gateway Time-Out`. 
Selon le site https://www.data.gouv.fr/fr/datasets/prix-des-carburants-en-france-flux-instantane/ il semblerait qu'une version v2 améliorée serait à utiliser à la place.

**Comment by nono031** [comment]
S'ils ont gardé la même représentation des données, il y a juste à changer 
[STATIONS_TARIFS_URL = "https://donnees.roulez-eco.fr/opendata/instantane"](https://github.com/Aohzan/hass-prixcarburant/blob/feef1a5bbddd26aed2acfa90ebe190295be87d06/custom_components/prix_carburant/tools.py#L27)

Si je trouve un peu de temps, j'essayerais...

**Comment by nono031** [comment]
Merci d'avoir testé, ça va demander un peu plus de travail alors... Je regarderai un soir en fin de semaine

**Comment by nono031** [comment]
C'est de retour mais je pense qu'il faudrait renommer l'issue: passage au [Flux instantané - v2 améliorée](https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/)

**Comment by nono031** [comment]
Euh... Je l'aurais clôturée si la transition vers le flux v2 avait été effectuée... Mais cela serait plus correct de faire une issue dédiée
