### ISSUE TITLE
Passage au flux instantané v2 

### ISSUE THREAD

**Issue by nono031** [Aohzan/hass-prixcarburant#12]
Après les recherches d'[Emeraude998](https://github.com/Emeraude998), il semblerait que le jeu de données du site web https://donnees.roulez-eco.fr/opendata/instantane ne sera bientôt plus maintenu

Selon le site [www.data.gouv.fr](https://www.data.gouv.fr/fr/datasets/prix-des-carburants-en-france-flux-instantane/), il faudrait  passer à la version v2 améliorée : https://www.data.gouv.fr/fr/datasets/prix-des-carburants-en-france-flux-instantane

Cela demande de reprendre l'API des requêtes et l'extraction des données.

---

After [Emeraude998](https://github.com/Emeraude998)'s research, it appears that the dataset from the website https://donnees.roulez-eco.fr/opendata/instantane will soon no longer be maintained.

According to the website [www.data.gouv.fr](http://www.data.gouv.fr/), it is necessary to switch to the improved v2 version: https://www.data.gouv.fr/fr/datasets/prix-des-carburants-en-france-flux-instantane

This requires revising the API requests and data extraction.

**Comment by electroromano** [comment]
Hello, @Aohzan 

As explained nono031 the migration of stations to the v2 feed has already started, 
several stations no longer communicate their prices via the v1 feed. 
Can you migrate your integration to the new v2 flow ?

Thanks

**Comment by Aohzan** [comment]
Yes I add this to my todo

**Comment by Aohzan** [comment]
migré en version 3.0.0 (beta actuellement)
