### ISSUE TITLE
Petites demandes d'ameilloration

### ISSUE THREAD

**Issue by jlg78fr** [Aohzan/hass-prixcarburant#13]
Bonjour

Cette nouvelle version est vraiment pratique !
2 petites demandes pour la prochaine version si possible
- ajout du logo "Auchan" dans sensor.py  - j'ai chargé un logo sur Wikipedia Communs (https://upload.wikimedia.org/wikipedia/commons/4/4f/Auchan_A.svg) mais il y a peut-être mieux...
 
- dans sensor.py, ligne 109, j'ai enlevé le "Station" dans le "station name" car je trouve que "Auchan Plaisir E10" suffit (plutôt que "Station Auchan Plaisir E10")

Merci encore pour tout le travail!

**Comment by Aohzan** [comment]
J'ai ajouté le logo dans la dernière version,
pour le nom je préfère laissé Station en préfixe par défaut, car il permet de retrouver et identifier facilement les appareils et entités

**Comment by jlg78fr** [comment]
Merci
Pour le nom, je pensais au "friendly name", pas le nom de l'entité
Cdt
Jean

**Comment by Aohzan** [comment]
C'est lié niveau développement, je défini un nom qui génère le friendly name et l'entité, puis l'utilisateur peut les personnaliser, l'un ou l'autre
