### ISSUE TITLE
Toutes petites choses

### ISSUE THREAD

**Issue by Userfreedu42** [Aohzan/hass-prixcarburant#14]
Bonjour et merci pour tout travail,

Les images des stations sont disponibles et tu as rajouté celle d'Auchan récemment, peux tu rajouter celle de Netto et Casino à l'occasion, merci bien

**Comment by Aohzan** [comment]
Est-ce possible de faire une PR directement, ou à minima donner le lien des logos en svg

**Comment by Gloird** [comment]
@Userfreedu42 je suis en train de réunir tout les logos des enseigne disponibles cela prend du temps 😅

@Aohzan Je compléterai ma PR quand j'aurai réuni tout les logos des grande enseignes.( Il y a beaucoup d'indépendant)

 Si vous voulez m'aider je vous met le lien vers mon sheets
https://docs.google.com/spreadsheets/d/1KKzss11qq4GsP9vZkRLPsdj0s32h4dLBCSeh6iDcu6U/edit?usp=drivesdk

**Comment by Aohzan** [comment]
Super merci 👍

**Comment by jlg78fr** [comment]
Bonjour
Le lien du logo d'Auchan a changé, il est maintenant 
https://upload.wikimedia.org/wikipedia/commons/a/aa/Auchan-A.svg
J'ai MAJ la sheet de @Gloird 
A l'occasion j'essaierai de trouver ou mettre sur wikipedia commons d'autres logos
Cdt
Jean

**Comment by Aohzan** [comment]
image auchan mise à jour en 3.2.0
