### ISSUE TITLE
Afficher les stations même en l'absence de données

### ISSUE THREAD

**Issue by nonobzh29** [Aohzan/hass-prixcarburant#29]
**Is your feature request related to a problem? Please describe.**
Avec les pénuries dans mon secteur en ce moment, certaines stations ne renvoient pas de données, car ne proposent plus de carburant.
Elle ne s'affichent donc plus sur la carte (ça encore ce n'est pas gênant), mais dans le dashboard ça met des "undefined" de partout.
Exemple :
![undefined](https://github.com/Aohzan/hass-prixcarburant/assets/17364399/5b5ba9ba-03f6-4aba-a912-7336be140b69)

Sur mobile ça a pour conséquence que le tableau dépasse sur la droite de la carte.

**Describe the solution you'd like**
Est-t-il possible d'afficher les stations (elles sont spécifiées dans la config yaml) même en l'absence de données ?
Quitte à afficher du vide, "N/A", ou "Erreur" pour le prix et la dernière update.

**Comment by Aohzan** [comment]
Normalement les entités restent là, elles passent juste en `unavailable`, tu n'as pas supprimé et réajouté l'intégration ?

**Comment by nonobzh29** [comment]
Non, je n'ai pas touché à l'intégration.

L'entité est bien là en effet :
![indispo](https://github.com/Aohzan/hass-prixcarburant/assets/17364399/fe698d4c-a46a-45cd-86a5-2a82f7275497)

J'ai l'impression que le soucis vient du fait que les attributs que j'utilise disparaissent dans ce cas (name (et pas friendly_name), days_since_last_update) :
![sensor](https://github.com/Aohzan/hass-prixcarburant/assets/17364399/44778d93-c859-4e6f-93ce-2adaed41a0e9)

Code de la carte :
```type: custom:flex-table-card
clickable: true
sort_by: state
entities:
  include: sensor.station*sp98
columns:
  - name: Station
    data: _name
  - name: €/L
    data: state
    modify: parseFloat(x).toFixed(3)
  - name: Màj
    data: days_since_last_update
    align: right
    suffix: ' j'
css:
  tbody tr:nth-child(1): 'color: #00ff00'
  tbody tr:nth-child(14): 'color: #f00020'
style: null
```

En fait, il faudrait pouvoir laisser les attributs même en l'absence de données, si c'est possible.

**Comment by Aohzan** [comment]
Ok je vois, je vais regarder

**Comment by Aohzan** [comment]
J'avais oublié de regardé… dans la prochaine version ,j'ai ajouté la restauration des entités, ça devrait fonctionner dans certains cas, par contre dans d'autres non pas de possibilité
