### ISSUE TITLE
Possibilité de ne prendre en compte que les stations declarées dans le Yaml.

### ISSUE THREAD

**Issue by Dim3333** [Aohzan/hass-prixcarburant#31]
Bonjour,

Une option supplémentaire serait de prendre en compte uniquement les stations déclarées dans le Yaml (en mettant 0 dans la distance par exemple).

Merci.

**Comment by Aohzan** [comment]
Bonjour
C'est déjà le cas, il faut juste déclarer la liste des stations

**Comment by Dim3333** [comment]
Pas sûr de comprendre.
Il n'est pas possible de mettre 0 comme distance dans la configuration. J'ai mis le minimum donc 1 et cela m'affiche des stations en plus de celles déclarées dans le Yaml.

**Comment by Aohzan** [comment]
il ne faut pas mettre du tout la clé `max_km` dans la conf, comme mis dans le README
https://github.com/Aohzan/hass-prixcarburant?tab=readme-ov-file#from-configurationyaml
si tu as la distance, c'est peut être parce que tu as configuré par l'UI puis en yaml, si c'est ça supprime l'intégration et redémarre

**Comment by Dim3333** [comment]
Dans le Yaml, je n'ai configuré que les Id des stations.
Lors de la configuration à l'installation, il est demandé la distance max. Il n'est pas possible de laisser le champ vide ou de mettre 0.
![image](https://github.com/Aohzan/hass-prixcarburant/assets/43283756/832bf41b-007b-48de-a654-762c81b165e0)
