### ISSUE TITLE
Error Prix carburant <-> Watchman

### ISSUE THREAD

**Issue by titou4307** [Aohzan/hass-prixcarburant#33]
**Describe the bug**
L'integration Watchman report un message de sensor absent : 

`person.me  | missing | custom_components/prix_carburant/services.yaml:9 
`
Comment faut il traiter la ligne pour que cette (mini) erreur n'apparaisse plus ? Par défaut un '#' ??

Peut être faut il préciser à quoi sert cette ligne pour les NewBee comme moi : )

Merci

**Comment by Aohzan** [comment]
je ne comprends pas ce qu'il manque exactement ? un service ? quel service ?

**Comment by titou4307** [comment]
Bonjour

Dans le fichier services.yaml de l'integration il a une entité "person.me"
C'est cette entité qui fait défaut ....

Que faut il mettre sur cette ligne à la place de person.me

Merci

**Comment by Aohzan** [comment]
c'est un exemple https://github.com/Aohzan/hass-prixcarburant/blob/d639048b6d8e09dbbaa67275f6177ba30b666b45/custom_components/prix_carburant/services.yaml#L5
dans les appels à ce service il faut mettre une entité `person`, du genre `person.titou`

**Comment by titou4307** [comment]
On est d'accord qu'il faut mettre un utilisateur existant dans  home assistant ,

si je suis ton exemple , j'ai un utilisateur par exemple titou à la connexion dans HA alors il faut mettre person.titou ou cela n'a rien a voir ?

Tu peux m'éclairer sur les appels de ce service ? à quoi sert il je ne comprends pas ce volet dans l'integration (newbee oblige)

Merci encore pour ton travail

**Comment by Aohzan** [comment]
je ne comprends pas l'erreur de ton watchman, mais si tu n'utilises pas le service, il n'y a pas de raison qu'il y ait une alerte

**Comment by titou4307** [comment]
Dans le fichier services.yaml cette entite est nommée....mais pas dans le fichier configuration.yaml peut etre...enfin je sais pas...
Peut etre faut il tout simplement commenter la ligne avec un #....

A quoi sert ce service ?

**Comment by Aohzan** [comment]
C'est indiqué en l'appelant
https://github.com/Aohzan/hass-prixcarburant/blob/master/custom_components/prix_carburant/translations/fr.json#L46
