### ISSUE TITLE
No icon for intermarché

### ISSUE THREAD

**Issue by Yoanf26** [Aohzan/hass-prixcarburant#34]
Hello,

I have all the icons for gas stations except for Intermarché.

![image](https://github.com/Aohzan/hass-prixcarburant/assets/38152898/b653c038-d66a-41c6-ab58-beac798c3d6f)

**Comment by pbranly** [comment]
So do I !

**Comment by Aohzan** [comment]
added in last release

**Comment by Yoanf26** [comment]
Thanks you very much. It's now ok.
