### ISSUE TITLE
Le logo pour Carrefour Market n'apparaît pas

### ISSUE THREAD

**Issue by Smashfer** [Aohzan/hass-prixcarburant#36]
Bonjour, je remarque que le logo de Carrefour Market n'apparaît pas. Dans le fichier sensor.py ligne 132, le lien vers le svg n'existe pas. Par contre le lien ligne 131 pour les autres Carrefour est correct.
Perso je vais utiliser le lien de la ligne 131.
PS : Merci pour le travail accompli :)

**Comment by Aohzan** [comment]
c'est possible de faire une PR pour corriger ?

**Comment by Smashfer** [comment]
Oui ok pour une Pull Request.
