### ISSUE TITLE
Aucune entité / données après installation

### ISSUE THREAD

**Issue by julienvedebe** [Aohzan/hass-prixcarburant#38]
**Describe the bug**
J'ai installé l'intégration via HACS (version 3.4.1) puis j'ai redémarré HA, j'ai ensuite ajouté l'intégration qui m'a proposé de configurer des types de carburants et une distance max.
Une fois ces opérations effectuée je n'ai aucun entités liées à l'intégration mis à part le bouton qui est censé refresh les données.
J'ai tenté de cliquer justement sur le bouton refresh de données il semble le faire correctement mais toujours aucune données.
J'ai voulu alors modifier la configuration de l'intégration via l'UI j'ai juste changé la distance pour mettre 10km cela ne fonctionne pas mieux mais j'ai relevé une erreur dans les journaux.

**Configuration**
From UI

**Expected behavior**
Je m'attend à voir les entités correspondant aux stations autour de chez moi

**Debug logs**

Paste debug logs here
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:202
First occurred: 21:26:41 (1 occurrences)
Last logged: 21:26:41

Error unloading entry Prix Carburant for sensor
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by Aohzan** [comment]
tu n'as pas d'autres log ? là il essaie de supprimer la configuration de l'intégration

**Comment by julienvedebe** [comment]
J'ai çà : 

Logger: homeassistant.config_entries
Source: config_entries.py:874
First occurred: 23:14:48 (1 occurrences)
Last logged: 23:14:48

Error occurred loading flow for integration ecole_directe: cannot import name 'TimestampDataUpdateCoordinator' from 'homeassistant.helpers.update_coordinator' (/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py)

merci pour ton aide

**Comment by Aohzan** [comment]
c'est lié à `ecole_directe`
est-ce que tu peux activer les logs en debug et recharger l'intégration puis copier les logs ici

**Comment by julienvedebe** [comment]
Oui effectivement c'est une autre intégration.

Je vais regarder comment mettre les logs en debug sinon j'ai trouvé celle-ci : 

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:202
First occurred: 18 mars 2024 à 21:26:41 (1 occurrences)
Last logged: 18 mars 2024 à 21:26:41

Error unloading entry Prix Carburant for sensor
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by Aohzan** [comment]
même message qu'au début, pour faire
https://github.com/Aohzan/ipx800v5/assets/2736322/4e2a69a3-db12-4c6d-9aa5-a96aa2e4a2e1

**Comment by julienvedebe** [comment]
J'ai activé le log spécifique puis rechargé l'intégration mais même erreur : 

![image](https://github.com/Aohzan/hass-prixcarburant/assets/12135264/640bfa4c-c0d5-42bb-820d-44f9f2db7f54)

**Comment by Aohzan** [comment]
en mettant en mode debug puis en arretant il va téléchagrer un fichier de log

**Comment by julienvedebe** [comment]
Arrêter HA ?

**Comment by julienvedebe** [comment]
voilà
[763265.txt](https://github.com/Aohzan/hass-prixcarburant/files/14654168/763265.txt)

**Comment by Aohzan** [comment]
voici la vraie erreur
`2024-03-18 21:19:59.169 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform prix_carburant.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/helpers/device_registry.py)).`

**Comment by Aohzan** [comment]
quelle version de HA utilises-tu ?

**Comment by julienvedebe** [comment]
Home Assistant 2023.7.3
Interface utilisateur : 20230705.1 - latest

**Comment by Aohzan** [comment]
Il faut mettre à jour, c'est lié au fait que tu utilises une vieille version

**Comment by julienvedebe** [comment]
ah mince c'est une version synology je ne sais pas si je peux

**Comment by julienvedebe** [comment]
merci en tout cas pour ton aide

**Comment by julienvedebe** [comment]
Merci encore pour ton aide j'ai réinstallé un HA en mode OS et maintenant tout fonctionne désolé pour la perte de temps.
