### ISSUE TITLE
Manque icone Leclerc

### ISSUE THREAD

**Issue by Overnuts** [Aohzan/hass-prixcarburant#42]
Pour la station 62138005 il manque l'icone 
c'est une station leclerc
j'ai survolé les issues précédentes, j'ai bien vu auchan et carrefour mais pas leclerc

(ha 24.4.2 - prixcarbu 3.5.2)

**Comment by Aohzan** [comment]
Je ne trouve pas la station dans le fichier https://github.com/Aohzan/hass-prixcarburant/blob/master/custom_components/prix_carburant/stations_name.json
Il faudrait faire une PR pour l'ajouter

**Comment by Overnuts** [comment]
corrigé avec  https://github.com/Aohzan/hass-prixcarburant/pull/43
