### ISSUE TITLE
Afficher le nom + la ville au lieu de l'ID

### ISSUE THREAD

**Issue by sebastienserre** [Aohzan/hass-prixcarburant#44]
Je pense que si le nom de la station etait systématiquement la marque  +la ville (Comme Auchan La Queue), ça aiderait à l'utilisation.
La j'ai du mal à identifier qui est qui.
![2024-04-16_22-36](https://github.com/Aohzan/hass-prixcarburant/assets/3902621/2f46115f-7cd5-4c98-b684-454d292c1b4a)

**Comment by Aohzan** [comment]
L'ID est mis si la station n'est pas connue en base, il faut les ajouter via une PR
