### ISSUE TITLE
localisation des stations

### ISSUE THREAD

**Issue by titof2375** [Aohzan/hass-prixcarburant#47]
Bonjour
es qu'il est possible que la localisation des station service ce fasse par rapport a la localisation du telephone  ou est installe l'app mobile de ha ?
On a dans instagration mobile de ha ce sensor ```sensor.XXXXXXX_XXXXX_7a_geocoded_location``` qui peut faire office de localisation.

**Comment by Aohzan** [comment]
il y a un service pour permet d'avoir les stations en fonction d'un mobile par exemple, cf README: 
> Un service est mis à disposition pour trouver le meilleur prix d'un carburant donné autour de soi ou de n'importe quelle entité possédant une localisation (device_tracker, person, sensor...).

**Comment by titof2375** [comment]
Merci, je ne savais pas que l'on pouver faire comme ca et pour mettre le resulta en carte tu a une astuce??????

**Comment by Aohzan** [comment]
ça par contre ce n'est pas possible car ça ne créé pas d'entité

**Comment by titof2375** [comment]
C'est justement ce que je demandais en faite, avoir une entité pour pouvoir faire une carte et comparer.

**Comment by Aohzan** [comment]
c'est pas possible dynamiquement

**Comment by titof2375** [comment]
J'ai fait une automatisation, et ça me demande un variable pour enregistrer la réponse, es que tu sais comment faire.

**Comment by Aohzan** [comment]
vu sur https://forum.hacf.fr/t/recuperer-les-prix-de-carburants/644/290
