### ISSUE TITLE
faire un sensor

### ISSUE THREAD

**Issue by titof2375** [Aohzan/hass-prixcarburant#48]
Bonjour, j'ai trouvée comment faire et si tu veut tu modifier la doc pour que tout le monde puissi faire la meme chose que moi .
alors déjà on peut faire un virtuel avec une varaible
`template: 
  - trigger:
      - platform: time_pattern
        minutes: /1
    action:
      - service: prix_carburant.find_nearest_stations
        data:
          distance: 10
          entity_id: device_tracker.XXXXX.XXX  # metre id de la personne a suivre
          fuel: Gazole                                         # metre les type de carburant
        response_variable: whatever                # la variable
    sensor:
      - name: test_stations                              # le mon du sensor
        unique_id: test_stations                        # id du sensor
        state: "{{ now().isoformat() }}"
        attributes:        
            stations: "{{ whatever.stations }}"      # metre la variable avec. station

`
Apres tu redemare ha  et tu a un nouveau sensor 

![resultat gazoil](https://github.com/Aohzan/hass-prixcarburant/assets/31250165/79a78e35-7702-431b-834c-aaadda2f8b41)

 Maitemant une carte, j'ai prix la flex

![gazol gazol](https://github.com/Aohzan/hass-prixcarburant/assets/31250165/24552757-4a9b-486c-93f0-d67180088c7a)

Et le code de la carte

`type: custom:flex-table-card
title: Christophe
clickable: true
sort_by: state
max_rows: 20
entities:
  include: sensor.test.stations
columns:
  - name: nom station
    data: stations
    modify: x.name
  - name: prix
    data: stations
    modify: x.price
    suffix: €
  - name: adresse station
    data: stations
    modify: x.address
    align: left
    suffix: J
css:
  tbody tr:nth-child(odd): 'background-color: rgba(255, 255, 255, 0.2)'
  tbody tr:nth-child(even): 'background-color: rgba(255, 255, 255, 0.1)'
card_mod:
  style: |`

voila c'est tout, il y a vingerha qui ma aidée aussi, je te remerci d'avoir lu ce poste et je suis a ta disposition si tu veut des info suplemantaire

**Comment by Aohzan** [comment]
Toutes les minutes c'est beaucoup :sweat_smile: tu risques de te faire bloquer par l'API, il faudrait à minima faire un trigger sur le changement de position avec un tempo de 30mn mini

**Comment by titof2375** [comment]
oui  c'est pas bete, apres c'etait pour les test qui fonctionne, apres je pense qu'il faut faire des réglages pour que ca fonctione correctement.

**Comment by LightD31** [comment]
Peux-tu utiliser des blocs de codes, je n'arrive pas à reproduire ton automatisation, comment fais-tu pour ajouter la partie sensor ?
```
Comme ceci
```
