### ISSUE TITLE
Probleme logos Auchan

### ISSUE THREAD

**Issue by Sabjul33** [Aohzan/hass-prixcarburant#54]
Le logo des stations Auchan n' apparaît plus.

L'url dans le fichier sensor.py n'est plus bonne (le logo n'existe pas)
case "Auchan":
self._attr_entity_picture = "https://upload.wikimedia.org/wikipedia/commons/4/4e/Logo_Auchan_A.png"

**Comment by Aohzan** [comment]
peux tu faire une PR

**Comment by Sabjul33** [comment]
PR = Pull request ?
Si c'est le cas j'ai essayé de trouver un logo sur wikimédia mais rien à par un vieux logo des années 60...

**Comment by Sabjul33** [comment]
Je viens de trouver une url qui fonctionne avec le bon logo.
https://upload.wikimedia.org/wikipedia/fr/c/cd/Logo_Auchan_%282015%29.svg
Je vais mettre à jour le fichier pour aller chercher le bon logo.
