### ISSUE TITLE
Update stations_name.json

### ISSUE THREAD

**Issue by Yoanf26** [Aohzan/hass-prixcarburant#59]
Bonjour,

Je n'ai pas le Auchan qui a remplacé Le géant à Montélimar.

Voici le code à ajouter dans stations_name.json

  "26200008": {
    "Nom": "Auchan Montélimar",
    "Marque": "Auchan"
  },

Merci

**Comment by Aohzan** [comment]
Merci de faire une PR directement

**Comment by Yoanf26** [comment]
C'est fait merci. Désolé de ne pas l'avoir fait directement.

**Comment by Aohzan** [comment]
Pas de soucis, c'est mergé
