### ISSUE TITLE
Mise a jour du code pour HA 2023.3

### ISSUE THREAD

**Issue by aqwserf** [Aohzan/hass-prixcarburant#6]
Bonjour @Aohzan @vingerha ,
suite à la mise à jour vers la version 2023.2, j'ai ces logs qui apparaissent:

```
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for prix_carburant using this method at custom_components/prix_carburant/__init__.py, line 10: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

Je suis ne pas developpeur expérimenté mais je pense qu'il ne s'agit que d'un changement de fonction sur la ligne mentionnée.

Serait-il possible de mettre l'extension à jour afin d'éviter des futures erreurs lors de la MAJ vers 2023.3 ?

Merci !

**Comment by Aohzan** [comment]
Hello,
je vais regarder ça

**Comment by vingerha** [comment]
j'ai testé ça dans init.py sur mon dev...plus d'erreurs et me semble que ça marche...mais sachant que je ne suis au top dans python :) 
```
async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up from a config entry."""
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    #hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    return True
```

**Comment by Aohzan** [comment]
Yes merci, nouvelle release => https://github.com/Aohzan/hass-prixcarburant/releases/tag/2.5.0
