### ISSUE TITLE
Modifier la liste des stations ?

### ISSUE THREAD

**Issue by inrepublica** [Aohzan/hass-prixcarburant#61]
**Describe the bug**
Je cherche à modifier la liste des stations.

**Configuration**
From UI

**Expected behavior**
J'ai du mal à trouver comment modifier la liste des stations après configuration par l'UI. En effet j'ai 16 stations ajoutés via la position du logement. Je souhaite en supprimer et en rajouter d'autres plus lointaine. Toutefois je ne trouve pas ou sont stockés les ID des stations... Je n'ai rien dans mon configuration.yaml ou dans sensor.yaml.

Merci pour cette intégration très utile!

**Comment by Aohzan** [comment]
Via l'UI tu pourras juste désactiver les entités des stations que tu ne veux pas, si tu veux une liste personnalisée, il faut passer par le configuration.yaml

**Comment by inrepublica** [comment]
Oui j'ai bien ajouté les stations qu'il me faut dans un sensor.yaml. Ma question est plus pour les autres ajoutés lors de l'installation du module PrixCarburant. On peut juste les désactiver du coup, pas de suppression ?
