### ISSUE TITLE
Error setting up entry Prix Carburant for prix_carburant

### ISSUE THREAD

**Issue by Sabjul33** [Aohzan/hass-prixcarburant#63]
J'ai cette erreur j'ai l'impression depuis la MAJ 2024.9.2.
Suis-je le seul ?

Voici le log d'erreur : 
Source: config_entries.py:604
Error setting up entry Prix Carburant for prix_carburant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/__init__.py", line 61, in async_setup_entry
    await tool.init_stations_from_location(
  File "/config/custom_components/prix_carburant/tools.py", line 146, in init_stations_from_location
    response_count = await self._request_api(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/tools.py", line 90, in _request_api
    raise PrixCarburantToolRequestError(
custom_components.prix_carburant.tools.PrixCarburantToolRequestError: API request error 404: {'error_code': 'NotFoundResource', 'message': 'The requested dataset prix-des-carburants-en-france-flux-instantane-v2 does not exist.'}

**Comment by vingerha** [comment]
API endpoint disparu ... nul

**Comment by Aohzan** [comment]
it's happening again...

**Comment by Sabjul33** [comment]
c'est à dire ?
Suis-je le seul ?

**Comment by Aohzan** [comment]
non, voir https://github.com/Aohzan/hass-prixcarburant/issues/46

**Comment by Sabjul33** [comment]
Ah ok c'est au niveau de l'url sur laquelle on tape qui a changé c'est bien ça ?

**Comment by Aohzan** [comment]
oui

**Comment by Aohzan** [comment]
enfin changé je sais pas, elle est plus dispo en tout cas actuellement

**Comment by alhousez** [comment]
J'ai trouvé une nouvelle adresse pour /homeassistant/custom_components/prix_carburant/tools.py

# PRIX_CARBURANT_API_URL = "https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/prix-des-carburants-en-france-flux-instantane-v2/records"
PRIX_CARBURANT_API_URL = "https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/prix-carburants-quotidien/records"
STATIONS_NAME_FILE = "stations_name.json"

mais la structure a aussi changé pour la latitude et la longitude
[

    {
        "id":"14710001",
        "geom":{
            "lon":-0.906,
            "lat":49.314
        }
        ,
        "cp":"14710",
        "adresse":"1 place Charles Delangle",
        "ville":"TREVIERES"
    }
    ,
et là, je ne sais pas encore faire

**Comment by Aohzan** [comment]
de ce que je comprends ce n'est plus une source instantanée mais mise à jour une fois par jour avec les infos de J-1

**Comment by alhousez** [comment]
Je viens de voir que l'API d'origine fonctionne à nouveau avec le flux instantané
https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/api/
Pas besoin de modifier /homeassistant/custom_components/prix_carburant/tools.py pour ce point

**Comment by Sabjul33** [comment]
Effectivement tout est reparti, j'ai de nouveaux toutes les infos 👌🥳🥳
