### ISSUE TITLE
The requested dataset prix-des-carburants-en-france-flux-instantane-v2 does not exist.'

### ISSUE THREAD

**Issue by tweevick01** [Aohzan/hass-prixcarburant#64]
**Describe the bug**

  File "/config/custom_components/prix_carburant/tools.py", line 90, in _request_api
    raise PrixCarburantToolRequestError(
custom_components.prix_carburant.tools.PrixCarburantToolRequestError: API request error 404: {'error_code': 'NotFoundResource', 'message': 'The requested dataset prix-des-carburants-en-france-flux-instantane-v2 does not exist.'

**Configuration**
Using the UI

**Expected behavior**
Return prices

**Screenshots**

**Debug logs**
![image](https://github.com/Aohzan/ipx800v5/assets/2736322/4e2a69a3-db12-4c6d-9aa5-a96aa2e4a2e1)
```
Paste debug logs here
```

**Comment by Kami-prog** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by Aohzan** [comment]
voir https://github.com/Aohzan/hass-prixcarburant/issues/63
