### ISSUE TITLE
Can you update stations_name.json

### ISSUE THREAD

**Issue by geekb** [Aohzan/hass-prixcarburant#68]
Hey, thanks for your project.
Can you add those two stations to stations_name.json ?

`
"77870002": {
  "Nom": "Auchan Vulaines-sur-Seine",
  "Marque": "Auchan"
},`
 `
"77000014": {
  "Nom": "Intermarché Vaux-le-pénil",
  "Marque": "Intermarché"
},
`

I don't know why i can't PR them,
cheers

**Comment by Aohzan** [comment]
will be done in next release
