### ISSUE TITLE
Get Price Data Info

### ISSUE THREAD

**Issue by lopezkevin** [Aohzan/hass-prixcarburant#7]
Hello Everybody,

The module work very well since 1 month , but since this morning, i can't receive the new data price info.

In the journal , i have this error log : 
[custom_components.prix_carburant.sensor] Error requesting prix_carburant data: <urlopen error [Errno -3] Try again>

Anybody have the same problem ?

**Comment by vingerha** [comment]
I cannot reproduce this, all is working fine / stable. Any chance the URL is not reachable from your machine?
