### ISSUE TITLE
[FR] Adding a fuel attribute

### ISSUE THREAD

**Issue by Nickduino** [Aohzan/hass-prixcarburant#70]
I'm displaying some E10 and SP95 stations in the same table and it would be convenient to have a fuel type attribute I could display in a column.

I could split the `friendly_name:` string and take the last word but not all cards will allow that and creating template sensors just for this seems like a big hassle compared to managing it with an attribute

**Comment by Nickduino** [comment]
I'll add more context because with most cards, you would need to add entities one by one and it would be easy to specify the name of the fuel. But I'm using `custom:flex-table-card` which allows to include all of them at once:

```
entities:
  include:
    - sensor.station_*E10
    - sensor.station_*SP95
    - sensor.station_*SP98
```

Then I sort them by price and display only the top 5. So I don't **know** what entities are or aren't shown

**Comment by Aohzan** [comment]
can you test the same PR  https://github.com/Aohzan/hass-prixcarburant/pull/71

**Comment by Aohzan** [comment]
done in 3.8.0
