### ISSUE TITLE
Readme update & retenu des statistiques

### ISSUE THREAD

**Issue by Tirguy** [Aohzan/hass-prixcarburant#8]
Bonjour Matthieu,

2 petites choses : 

- Le fichier readme.md fait toujours référence à https://github.com/vingerha/prixCarburant-home-assistant; une petite MaJ s'impose ;-)
- Je voulais afficher un graphique sur l'évolution des données de certaines stations dans mon HA, mais le système me dit qu'il faut que je te rappel ceci : https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics  ;-)

Crois tu qu'il serait possible de corriger et d'ajouter cette fonctionnalité ? 

Merci,
Thierry

**Comment by vingerha** [comment]
Bjr
1. fixé le readme
2. créer des statistiques n'est pas pour le sensor et presque impossible car on ne sait pas quelle sensor à inclure, toi t'as des sensor différent que moi ayant dans un autre endoit et type de carburant  Il faut utiliser les fonctionalaités de HA pour le faire. p.e. https://www.home-assistant.io/integrations/statistics/

Sans commentaire sur 2, dans la semaine, je vais terminer / clos ce ticket
